# Generated by Django 4.1.4 on 2022-12-20 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Partner',
            new_name='Addict',
        ),
        migrations.RenameModel(
            old_name='Volunteer',
            new_name='Professional',
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('is_admin', 'Admin'), ('is_professional', 'Professional'), ('is_addict', 'Addict')], max_length=20),
        ),
    ]
