# Generated by Django 4.1.4 on 2022-12-21 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_contact_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PartnerInfo',
            new_name='Diagnosis',
        ),
        migrations.RenameModel(
            old_name='VolunteerInfo',
            new_name='Questions',
        ),
        migrations.RenameModel(
            old_name='Announcement',
            new_name='Testimonies',
        ),
    ]
