# Generated by Django 4.1.4 on 2022-12-21 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_partnerinfo_diagnosis_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosis',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
