# Generated by Django 4.1.4 on 2022-12-21 13:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_questions_id_alter_recommendations_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Approve',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('approveTF', models.CharField(blank=True, max_length=1)),
                ('date', models.DateField(null=True)),
                ('testimony_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.testimonies')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
