# Generated by Django 4.1.4 on 2022-12-21 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_approve'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonies',
            name='date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
