# Generated by Django 4.1.4 on 2022-12-21 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_answers_date_alter_approve_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approve',
            name='approveTF',
            field=models.CharField(blank=True, max_length=1, unique=True),
        ),
    ]
