# Generated by Django 4.1.4 on 2022-12-21 20:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_approve_approvetf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approve',
            name='approveTF',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AlterField(
            model_name='approve',
            name='testimony_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.testimonies', unique=True),
        ),
        migrations.AlterField(
            model_name='testimonies',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
