# Generated by Django 4.1.4 on 2022-12-21 20:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_approve_approvetf_alter_approve_testimony_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approve',
            name='testimony_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.testimonies'),
        ),
        migrations.AlterField(
            model_name='testimonies',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
