# Generated by Django 4.1.4 on 2022-12-26 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_approve_testimony_id_alter_testimonies_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answers',
            old_name='date',
            new_name='answer_date',
        ),
        migrations.RenameField(
            model_name='answers',
            old_name='message',
            new_name='answer_message',
        ),
        migrations.RenameField(
            model_name='answers',
            old_name='subject',
            new_name='answer_subject',
        ),
        migrations.RenameField(
            model_name='questions',
            old_name='date',
            new_name='question_date',
        ),
        migrations.RenameField(
            model_name='questions',
            old_name='message',
            new_name='question_message',
        ),
        migrations.RenameField(
            model_name='questions',
            old_name='subject',
            new_name='question_subject',
        ),
    ]
