# Generated by Django 4.1.4 on 2022-12-27 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_rename_date_answers_answer_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diagnosis',
            old_name='date',
            new_name='diagnosis_date',
        ),
        migrations.RenameField(
            model_name='diagnosis',
            old_name='message',
            new_name='diagnosis_message',
        ),
        migrations.RenameField(
            model_name='diagnosis',
            old_name='subject',
            new_name='diagnosis_subject',
        ),
        migrations.RenameField(
            model_name='recommendations',
            old_name='date',
            new_name='recommendation_date',
        ),
        migrations.RenameField(
            model_name='recommendations',
            old_name='message',
            new_name='recommendation_message',
        ),
        migrations.RenameField(
            model_name='recommendations',
            old_name='subject',
            new_name='recommendation_subject',
        ),
    ]
